# Generated by Django 5.2.6 on 2025-09-12 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_bookingtable_booking_rename_menutable_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
